"""Model o'zgarishlari

Revision ID: d6c43825e8dc
Revises: 8bb146f203e3
Create Date: 2025-05-08 23:21:07.321240

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d6c43825e8dc"
down_revision: Union[str, None] = "8bb146f203e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("added_date", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_group_id"), "user_group", ["id"], unique=False
    )
    op.add_column(
        "attendances", sa.Column("user_group_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "attendances", "user_group", ["user_group_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "attendances", type_="foreignkey")
    op.drop_column("attendances", "user_group_id")
    op.drop_index(op.f("ix_user_group_id"), table_name="user_group")
    op.drop_table("user_group")
    # ### end Alembic commands ###
